# ===============================
# Application Configuration
# ===============================

# Application name
spring.application.name=OrderService

# Port
server.port=9092

# ===============================
# MongoDB Atlas Configuration
# ===============================
spring.data.mongodb.uri=${ORDER_MONGODB_URI:}
# ===============================
# Logging Configuration
# ===============================

# Global log level
logging.level.root=INFO

# Log level for your application package (adjust based on your actual package name)
logging.level.com.GroupProject.OrderService=DEBUG

# Log output file
logging.file.name=logs/order-service.log

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Optional: Enable color for console logs (Spring Boot automatically does this when supported)
# logging.color=always

razorpay.key_id=${RAZORPAY_KEY_ID:}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ORDER_MAIL_USERNAME:}
spring.mail.password=${ORDER_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
