spring.application.name=AuthService
server.port=8081

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://mayurkotwal75:rentcart123@rentcart.rpnqlbb.mongodb.net/rentcart?retryWrites=true&w=majority&appName=RentCart

# Email configuration for password reset
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vedantsalvi2353@gmail.com
spring.mail.password=mlnt wsma pcwi earx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
