# Application name
spring.application.name=OrderService

# Port
server.port=9090

# MongoDB Atlas configuration
spring.data.mongodb.uri=mongodb+srv://mayurkotwal75:rentcart123@rentcart.rpnqlbb.mongodb.net/rentcart?retryWrites=true&w=majority&appName=RentCart

# Logging level
logging.level.org.springframework=INFO
